"""Schema-driven authoring templates for phase-two plugin SDK workflows."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Literal

from .manifest import DEFAULT_PLUGIN_MANIFEST_VERSION, load_plugin_manifest

PluginTemplateKind = Literal["tool", "hook", "hybrid"]


@dataclass(frozen=True)
class PluginTemplateSpec:
    """Structured input for generating a starter plugin bundle on disk."""

    plugin_id: str
    name: str
    description: str
    template_kind: PluginTemplateKind = "tool"
    version: str = "0.0.1"
    manifest_version: int = DEFAULT_PLUGIN_MANIFEST_VERSION
    entrypoint: str = "main.py"
    dependencies: list[str] = field(default_factory=list)
    config_schema: Dict[str, Any] = field(default_factory=lambda: {"type": "object"})
    default_config: Dict[str, Any] = field(default_factory=dict)
    distribution: Dict[str, Any] = field(default_factory=dict)
    release_notes: str = ""
    tool_names: list[str] = field(default_factory=list)
    capability_kind: str = "tool"

    @property
    def capability_id(self) -> str:
        return f"plugin:{self.plugin_id}.main"

    @property
    def display_name(self) -> str:
        return self.name or self.plugin_id


def _pretty_json(value: Dict[str, Any]) -> str:
    return json.dumps(value, indent=2, sort_keys=True)


def _manifest_from_spec(spec: PluginTemplateSpec) -> Dict[str, Any]:
    tool_names = list(spec.tool_names)
    if not tool_names and spec.template_kind in {"tool", "hybrid"}:
        tool_names = [f"{spec.plugin_id}_tool"]
    return {
        "manifest_version": spec.manifest_version,
        "id": spec.plugin_id,
        "name": spec.name,
        "description": spec.description,
        "version": spec.version,
        "entrypoint": spec.entrypoint,
        "dependencies": list(spec.dependencies),
        "config_schema": dict(spec.config_schema),
        "default_config": dict(spec.default_config),
        "distribution": dict(spec.distribution),
        "release_notes": spec.release_notes,
        "capabilities": [
            {
                "capability_id": spec.capability_id,
                "display_name": spec.display_name,
                "kind": spec.capability_kind,
                "description": spec.description,
                "tool_names": tool_names,
            }
        ],
    }


def _render_entrypoint(spec: PluginTemplateSpec) -> str:
    config_schema_literal = _pretty_json(dict(spec.config_schema))
    default_config_literal = _pretty_json(dict(spec.default_config))
    tool_names = list(spec.tool_names)
    if not tool_names and spec.template_kind in {"tool", "hybrid"}:
        tool_names = [f"{spec.plugin_id}_tool"]
    capability_list = ", ".join(repr(name) for name in tool_names)

    sections: list[str] = [
        '"""Plugin entrypoint generated by the OpenCAS phase-two SDK scaffolder."""',
        "",
        "from __future__ import annotations",
        "",
        "from opencas.plugins.models import SkillEntry",
        "",
        f"CONFIG_SCHEMA = {config_schema_literal}",
        f"DEFAULT_CONFIG = {default_config_literal}",
        "",
    ]

    if spec.template_kind in {"tool", "hybrid"}:
        sections.extend(
            [
                "def register_skills(skill_registry, tools):",
                '    """Register skills and TODO tool bindings for this plugin."""',
                "    skill_registry.register(",
                "        SkillEntry(",
                f"            skill_id={spec.plugin_id!r},",
                f"            name={spec.name!r},",
                f"            description={spec.description!r},",
                f"            capabilities=[{capability_list}],",
                "        )",
                "    )",
                "    # TODO: register one or more tools with `tools.register(...)`.",
                "    # The manifest already declares the intended tool names.",
                "",
            ]
        )

    if spec.template_kind in {"hook", "hybrid"}:
        sections.extend(
            [
                "def example_hook(payload, ctx):",
                '    """TODO: replace with real hook behavior."""',
                "    return payload",
                "",
                "def register_hooks(registry):",
                '    """Register lifecycle or policy hooks for this plugin."""',
                "    # TODO: replace `example_hook` and `example.event` with the desired hook contract.",
                f"    registry.register('example.event', example_hook, source={spec.plugin_id!r})",
                "",
            ]
        )

    sections.extend(
        [
            "def get_default_config():",
            '    """Return the default config payload mirrored in plugin.json."""',
            "    return dict(DEFAULT_CONFIG)",
            "",
        ]
    )

    return "\n".join(sections).rstrip() + "\n"


def _render_readme(spec: PluginTemplateSpec) -> str:
    tool_summary = ", ".join(spec.tool_names or [f"{spec.plugin_id}_tool"])
    return (
        f"# {spec.name}\n\n"
        "This plugin scaffold was generated by the OpenCAS phase-two SDK template helper.\n\n"
        "## Next Steps\n"
        "1. Implement the TODO sections in `main.py`.\n"
        "2. Keep `plugin.json` as the source of truth for manifest metadata and config schema.\n"
        "3. Fill in `distribution` and `release_notes` so operators can inspect provenance before install/update.\n"
        "4. Optionally sign the directory with `sign_plugin_directory(...)` before packaging when you want cryptographic provenance.\n"
        "5. Package the directory with `build_plugin_bundle(...)` when you want a distributable archive.\n\n"
        "## Template Summary\n"
        f"- Plugin ID: `{spec.plugin_id}`\n"
        f"- Template kind: `{spec.template_kind}`\n"
        f"- Declared capability: `{spec.capability_id}`\n"
        f"- Declared tools: `{tool_summary}`\n"
        f"- Manifest version: `{spec.manifest_version}`\n"
        f"- Distribution metadata keys: `{', '.join(sorted(spec.distribution.keys())) or 'none yet'}`\n"
    )


def scaffold_plugin_template(
    target_dir: Path | str,
    spec: PluginTemplateSpec,
) -> Path:
    """Generate a starter plugin directory and return the manifest path."""

    target_dir = Path(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = target_dir / "plugin.json"
    manifest_path.write_text(_pretty_json(_manifest_from_spec(spec)) + "\n", encoding="utf-8")

    entrypoint_path = target_dir / spec.entrypoint
    entrypoint_path.parent.mkdir(parents=True, exist_ok=True)
    entrypoint_path.write_text(_render_entrypoint(spec), encoding="utf-8")

    readme_path = target_dir / "README.md"
    readme_path.write_text(_render_readme(spec), encoding="utf-8")

    # Validate the generated manifest immediately so scaffolds never emit stale contracts.
    load_plugin_manifest(manifest_path)
    return manifest_path
